
# Spring Boot App Deployment & NodePort Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-book-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-book-mongo
  template:
    metadata:
      labels:
        app: spring-book-mongo
    spec:
      containers:
        - name: spring-book-mongo
          image: spring-book-mongo:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://root:rootpass@kgmongo:27017/book?authSource=admin
            - name: SPRING_DATA_REDIS_HOST
              value: kgredis
---
apiVersion: v1
kind: Service
metadata:
  name: spring-book-mongo
spec:
  type: NodePort
  selector:
    app: spring-book-mongo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30626  # Optional: set or remove for auto assignment
