# MongoDB Deployment & Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kgmongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kgmongo
  template:
    metadata:
      labels:
        app: kgmongo
    spec:
      containers:
        - name: mongo
          image: mongo:7.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: rootpass
---
apiVersion: v1
kind: Service
metadata:
  name: kgmongo
spec:
  selector:
    app: kgmongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---

# Redis Deployment & Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kgredis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kgredis
  template:
    metadata:
      labels:
        app: kgredis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: kgredis
spec:
  selector:
    app: kgredis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---

# Spring Boot App Deployment & NodePort Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-book-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-book-mongo
  template:
    metadata:
      labels:
        app: spring-book-mongo
    spec:
      containers:
        - name: spring-book-mongo
          image: spring-book-mongo:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://root:rootpass@kgmongo:27017/book?authSource=admin
            - name: SPRING_DATA_REDIS_HOST
              value: kgredis
---
apiVersion: v1
kind: Service
metadata:
  name: spring-book-mongo
spec:
  type: NodePort
  selector:
    app: spring-book-mongo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30626  # Optional: set or remove for auto assignment
