
services:
  kgmongo:
    image: mongo:latest
    container_name: "kgmongo"
    ports:
      - 27017:27017

  kgRedis:
    image: redis
    container_name: "kgRedis"
    ports:
      - 6379:6379

  spring-book-mongo:
    image: spring-book-mongo:1.0
    container_name: spring-book-mongo
    ports:
      - 8080:8080
    links:
      - kgmongo
      - kgRedis


