# MongoDB Deployment & Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kgmongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kgmongo
  template:
    metadata:
      labels:
        app: kgmongo
    spec:
      containers:
        - name: mongo
          image: mongo:7.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: rootpass
---
apiVersion: v1
kind: Service
metadata:
  name: kgmongo
spec:
  selector:
    app: kgmongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
