# Redis Deployment & Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kgredis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kgredis
  template:
    metadata:
      labels:
        app: kgredis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: kgredis
spec:
  selector:
    app: kgredis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
